# Generated by Django 5.0.1 on 2024-02-04 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vue', '0008_remove_data_confidence_score_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostStudy',
            new_name='PostStudyData',
        ),
        migrations.RenameModel(
            old_name='PreStudy',
            new_name='PreStudyData',
        ),
        migrations.RenameModel(
            old_name='Training',
            new_name='TrainingData',
        ),
    ]
