# Generated by Django 5.0.1 on 2024-02-04 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vue', '0009_rename_poststudy_poststudydata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='slide_numbers',
        ),
        migrations.RemoveField(
            model_name='trainingdata',
            name='slide_numbers',
        ),
    ]
