# Generated by Django 5.0.1 on 2024-02-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue', '0012_remove_trainingdata_confidence_scores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='confidence_scores',
        ),
        migrations.RemoveField(
            model_name='data',
            name='tcp_ests',
        ),
        migrations.RemoveField(
            model_name='trainingdata',
            name='tcp_ests',
        ),
        migrations.AddField(
            model_name='data',
            name='confidence_score',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='slide',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='tcp_est',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='confidence_score',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='slide',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='tcp_est',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
