# Generated by Django 5.0.1 on 2024-02-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue', '0014_rename_status_experiment_statusbaseline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poststudydata',
            name='UEQ_answers',
        ),
        migrations.AddField(
            model_name='poststudydata',
            name='item1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='poststudydata',
            name='item2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='poststudydata',
            name='item3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='poststudydata',
            name='item4',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='poststudydata',
            name='item5',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='poststudydata',
            name='item6',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='poststudydata',
            name='item7',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='poststudydata',
            name='item8',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
