# Generated by Django 5.0.1 on 2024-02-11 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vue', '0015_remove_poststudydata_ueq_answers_poststudydata_item1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingdata',
            name='confidence_score',
        ),
    ]
