# Generated by Django 5.0.1 on 2024-02-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue', '0016_remove_trainingdata_confidence_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='poststudydata',
            name='question1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='poststudydata',
            name='question2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='poststudydata',
            name='question3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='poststudydata',
            name='question4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='poststudydata',
            name='question5',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='poststudydata',
            name='question6',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
